### ISSUE TITLE
关于在Vue项目中使用vw实现移动端适配这篇文章中的一些疑问

### ISSUE THREAD

**Issue by wjryours** [airen/vw-layout#1]
大漠老师你好，我最近看了你这个Vue项目中使用vw实现移动端适配这篇文章收获很大，但是我有个小疑问，就是在这个项目中对于不需要px转换vw的样式添加ignore类名时，如果不需要转换的样式数量很大时，我该怎么解决呢？而且这个ignore类名重复使用时也会存在样式冲突，请老师指教下。

**Comment by airen** [comment]
目前只有添加类名来解决，对于同类似的样式冲突，你在写样式的时候，可以添加父元素选择器。
